/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as AteliesSlugRouteImport } from './routes/atelies.$slug'
import { Route as CostureirasSlugRouteImport } from './routes/costureiras.$slug'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AteliesSlugRoute = AteliesSlugRouteImport.update({
  id: '/atelies/$slug',
  path: '/atelies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CostureirasSlugRoute = CostureirasSlugRouteImport.update({
  id: '/costureiras/$slug',
  path: '/costureiras/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CursosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/atelies/$slug': typeof AteliesSlugRoute
  '/costureiras/$slug': typeof CostureirasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/atelies/$slug': typeof AteliesSlugRoute
  '/costureiras/$slug': typeof CostureirasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/atelies/$slug': typeof AteliesSlugRoute
  '/costureiras/$slug': typeof CostureirasSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cursos'
    | '/mapa'
    | '/perfil'
    | '/atelies/$slug'
    | '/costureiras/$slug'
    | '/cursos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cursos'
    | '/mapa'
    | '/perfil'
    | '/atelies/$slug'
    | '/costureiras/$slug'
    | '/cursos/$slug'
  id:
    | '__root__'
    | '/'
    | '/cursos'
    | '/mapa'
    | '/perfil'
    | '/atelies/$slug'
    | '/costureiras/$slug'
    | '/cursos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursosRoute: typeof CursosRouteWithChildren
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRoute
  AteliesSlugRoute: typeof AteliesSlugRoute
  CostureirasSlugRoute: typeof CostureirasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelies/$slug': {
      id: '/atelies/$slug'
      path: '/atelies/$slug'
      fullPath: '/atelies/$slug'
      preLoaderRoute: typeof AteliesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costureiras/$slug': {
      id: '/costureiras/$slug'
      path: '/costureiras/$slug'
      fullPath: '/costureiras/$slug'
      preLoaderRoute: typeof CostureirasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof CursosRoute
    }
  }
}

interface CursosRouteChildren {
  CursosSlugRoute: typeof CursosSlugRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosSlugRoute: CursosSlugRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursosRoute: CursosRouteWithChildren,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRoute,
  AteliesSlugRoute: AteliesSlugRoute,
  CostureirasSlugRoute: CostureirasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
